name: Build

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore .\WiderCodex\WiderCodex.csproj

      - name: Build
        run: dotnet build .\WiderCodex\WiderCodex.csproj --configuration Release --no-restore
